### ISSUE TITLE
Docker Socket Proxy permissions incorrect in documentation

### ISSUE THREAD

**Issue by Dan-Ev** [Notifiarr/dockwatch#45]
I had some trouble updating containers after configuring Dockwatch with docker socket proxy. The permissions required listed in the documentation are incomplete. I had to update them to the following to be able to successfully perform updated:  

```
- ALLOW_START=1
- ALLOW_STOP=1
- ALLOW_RESTARTS=1
- CONTAINERS=1
- IMAGES=1
- NETWORKS=1
- POST=1
- VOLUMES=1
```
The documentation lists PORTS but I can't see why this is enabled so deleted it. (Typo of POST ?)
POST, START, STOP are required to update containers.
RESTARTS allows restarting from the Dockwatch interface

**Comment by austinwbest** [comment]
Thanks for the info, i am pretty sure PORTS would be needed because of https://github.com/Notifiarr/dockwatch/blob/a50c8a9216e591f15cee9392dbc526101dae2ec9/root/app/www/public/classes/traits/Docker/Container.php#L12-L16

As the socket proxy changes and as dockwatch changes im sure we'll have to make adjustments to the wiki so i'll add your additions to it

**Comment by Dan-Ev** [comment]
The quoted code looks like it should require the PORTS permission, but I still see ports listed on the main page and the containers page with it disabled. It might be that these values are populated from compose environment variables, but for me at least it's working.

Thanks for updating the wiki. I'll close this issue as complete.
